baseURL: https://sotagburners.github.io
languageCode: en-gb
title: SOTagBurners
publishDir: public

uglyurls: true

taxonomies:
  category: categories
  tag: tags

outputs:
  taxonomy: ["HTML"]
  taxonomyTerm: ["HTML"]
  page: ["HTML"]
  # Not sure if this affects blog RSS, if we eventually add one.
  # Future problem, though.
  section: ["HTML"]
  home: ["HTML"]

markup:
  enableEmoji: true
  goldmark:
    extensions:
      linkify: true
      typographer: false
    renderer:
      unsafe: true
  highlight:
    style: emacs
  tableOfContents:
    endLevel: 6
    startLevel: 2

menus:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: faq
      name: FAQ
      url: /faq
      weight: 2
    - identifier: contribute
      name: Contribute
      url: /contribute
      weight: 3
    - identifier: about
      name: About Us
      url: /about
      weight: 4
